_target_: src.models.components.policies.transformer.TransformerPolicy
model_type: CCT
cfg:
  img_size: [6, 20]
  n_input_channels: 64 # should be consistent with the feature extractor
  embedding_dim: 
  n_conv_layers: 3
  kernel_size: 1
  stride: 1
  padding: 0
  pooling_kernel_size: 3
  pooling_stride: 1
  pooling_padding: 1
  num_layers: 3
  num_heads: 4
  mlp_ratio: 3.
  num_classes: 2
  positional_embedding: learnable
